services:

  # ── Database
  postgres:
    image: postgres:17
    container_name: inventory-postgres
    restart: always
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventorydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web-network

  # ── Backend (Spring Boot)
  backend:
    build:
      context: ./backend
    container_name: inventory-backend
    restart: always
#    ports:
#      - "8080:8080"
    expose:
       - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventorydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      JWT_SECRET: change-this-secret-key-please-use-a-longer-secret-key-1234567890
      JWT_EXPIRATION: 86400000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - web-network

  # ── Frontend (React → nginx) ──────────────────────────────
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://api-inventory-manager.tahableu.me/api
    container_name: inventory-frontend
    restart: always
#    ports:
#      - "3000:80"
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - web-network

volumes:
  inventory_postgres_data:

networks:
  web-network:
    external: true
    name: web-network
