spring.datasource.url=jdbc:postgresql://localhost:5432/inventorydb
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=change-this-secret-key-please-use-a-longer-secret-key-1234567890
jwt.expiration=86400000
